---
- hosts: test
  # this is by default YES. So no need mention it anyway
  gather_facts: yes
  tasks:
    # Getting the IP address of enp0s3 interface of a remote machines listed in the test host group.
    #- debug: var=ansible_enp0s3.ipv4.address
    # Getting the IP address of eth0 interface
    - debug: var=ansible_eth0.ipv4.address
