---

- hosts: all
  become: yes

  tasks:
    - name: Check the status of sshd
      command: systemctl status sshd
      register: output

    - name: Restarting sshd
      service:
        name: sshd
        state: restarted 
      
    - name: Show output
      debug: var=output
