---

- hosts: all
  become: yes

  tasks:
    - name: Checking SSM agent version
      command: yum info amazon-ssm-agent | grep "Version"
      register: output
      
    - name: Restarting SSM agent
      service: 
        name: amazon-ssm-agent
        state: restarted
        #enabled: yes
      
    - name: Show output
      debug: var=output
